[웹 개발 상식]

server : 기능을 제공하는 컴퓨터

Client : 기능을 요청하고 이용하는 고객 컴퓨터

        요청(Request) --->
Client                      server
        <--- 응답(Response)

-----------------------------------------------------

HTTP(Hyper Text Transfer Protocol)
- 서버 - 클라이언트 간의
  HTML 요청 - 응답 전송(전달)규약
  (인터넷에서 HTML을 주고 받을 때의 약속)

IP(Internet Protocol)
 : 인터넷/네트워크를 통해 데이터를 송수신하는 규약
  -> 인터넷/네트워크에 연결된 각종 통신기기를 구분하는 주소
     (컴퓨터, 휴대폰, 단말기 등등)

IPv6 주소 . . . . : fe80::29cf:6738:7e6c:a283%5
IPv4 주소 . . . . : 192.168.10.17

Port 번호 : 컴퓨터 내 프로그램을 구분하는 식별 번호

IP + Port 번호를 알아야
다른 컴퓨터(서버)에 요청을 할 수 있다
ex) http:// 192.168.10.5:8080


bin 에서 cmd 후 startup.bat
후 인터넷 에서 127.0.0.1:8080 or localhost:8080

제너럴 - show heap status
       - 아래 워크 스페이스 - refresh using native
font - 컬러 앤 폰트 - 베이직 - 맨 아래 text font

Runtime Environment -> Add -> Apache -> Apache Tomcat 10.1 선택 후 Next
압축 푼 아파치 선택


-------------------[Servlet]----------------------
클라이언트의 요청(Request)을 처리하고
그 결과를 다시 클라이언트에게 응답(Response)하는
Servlet클래스의 구현 규칙을 지킨 자바 프로그래밍 기술

브라우저 : HTML 해석 도구, 서버 요청